apiVersion: v1
kind: Pod
metadata:
  name: b1-1
spec:
  restartPolicy: Never
  containers:
  - name: b1-1
    image: python:3.6
    command: ["python", "B1_1.py"]
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    livenessProbe:
      exec:
        command:
        - python
        - -c
        - "import sys; sys.exit(0) if 'Alice' in open('output.txt').read() else sys.exit(1)" # Check for expected output
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - python
        - -c
        - "import sys; sys.exit(0)" # Simple check if the process is running
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
    - name: output-volume
      mountPath: /app
  volumes:
  - name: output-volume
    emptyDir: {} # Use emptyDir for ephemeral storage