apiVersion: v1
kind: Pod
metadata:
  name: b1-1
spec:
  restartPolicy: Never
  containers:
  - name: b1-1
    image: python:3.6
    command: ["python", "/app/b1_1.py"]
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    livenessProbe:
      exec:
        command: ["python", "-c", "import sys; sys.exit(0)"]
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      exec:
        command: ["python", "-c", "import sys; sys.exit(0)"]
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
    - name: code-volume
      mountPath: /app
  volumes:
  - name: code-volume
    configMap:
      name: b1-1-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b1-1-configmap
data:
  b1_1.py: |
    def greet(name):
        print(f"Hello, {name}!")

    if __name__ == "__main__":
        greet("Alice")